repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        files: ^(reader_rbv|tests)/.*\.py$
        args:
          - --diff
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          - --ignore=E501
  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.7.2
    hooks:
      - id: pylint
        files: ^reader_rbv/.*\.py$
        args:
          - --errors-only
          - --disable=import-error
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
        files: ^reader_rbv/.*\.py$